name: mthimm
favicon: null
layout_spectrum: 0.37853042129427195
typography_spectrum: 0.9557866062968969
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.07401987793855369
  lightness: 0.5621938521508127
  saturation: 0.7278353690635413
  rhythmicContrast: 0.7756833510939032
purpose: []
